USE BookEStore;
CREATE TABLE TACGIA (
  ID char(3) PRIMARY KEY,
  NAME TINYTEXT NOT NULL
);

CREATE TABLE DANHMUCSACH (
  ID char(2) PRIMARY KEY,
  NAME TINYTEXT NOT NULL
);

CREATE TABLE NHAXUATBAN (
  ID char(3) PRIMARY KEY,
  NAME TINYTEXT NOT NULL
);

CREATE TABLE THONGTINSACH (
  ID char(4) PRIMARY KEY,
  NAME TINYTEXT NOT NULL,
  IMAGE TINYTEXT NOT NULL,
  PRICE INT UNSIGNED NOT NULL,
  VIEWS MEDIUMINT UNSIGNED,
  SALES MEDIUMINT UNSIGNED,
  INVENTORY MEDIUMINT UNSIGNED,
  DESCRIPTION MEDIUMTEXT NOT NULL,
  ID_AUTHOR char(3) NOT NULL,
  ID_CATEGORY char(2) NOT NULL,
  ID_PUBLISHER char(3) NOT NULL
);

CREATE TABLE NGUOIDUNG (
  ID char(4) PRIMARY KEY,
  NAME TINYTEXT,
	GENDER CHAR(10),
	BIRTHDAY DATE,
  EMAIL TINYTEXT NOT NULL,
  PASSWORD TINYTEXT NOT NULL
);

CREATE TABLE DONHANG (
  ID char(6) PRIMARY KEY,
  ID_USER char(4) NOT NULL,
  DATE_CREATED DATE NOT NULL,
  CONTENT MEDIUMTEXT,
  TOTAL_COST INT UNSIGNED NOT NULL,
  STATE TINYINT NOT NULL DEFAULT 0
	
);

/*************************** SET CONSTRAINT ***************************/
-- ALTER TABLE TACGIA ADD PRIMARY KEY (ID);
-- 
-- ALTER TABLE DANHMUCSACH ADD PRIMARY KEY (ID);
-- 
-- ALTER TABLE NHAXUATBAN ADD PRIMARY KEY (ID);

-- ALTER TABLE THONGTINSACH PRIMARY KEY (ID);
ALTER TABLE THONGTINSACH ADD FOREIGN KEY (ID_AUTHOR) REFERENCES TACGIA(ID);
ALTER TABLE THONGTINSACH ADD FOREIGN KEY (ID_CATEGORY) REFERENCES DANHMUCSACH(ID);
ALTER TABLE THONGTINSACH ADD FOREIGN KEY (ID_PUBLISHER) REFERENCES NHAXUATBAN(ID);
ALTER TABLE THONGTINSACH ADD CHECK (PRICE >= 0 AND VIEWS >=0 AND SALES >= 0 AND INVENTORY >= 0);

-- ALTER TABLE NGUOIDUNG ADD PRIMARY KEY (ID);

-- ALTER TABLE DONHANG ADD PRIMARY KEY (ID);
ALTER TABLE DONHANG ADD FOREIGN KEY (ID_USER) REFERENCES NGUOIDUNG(ID);
ALTER TABLE DONHANG ADD CHECK (TOTAL_COST >= 0);
