USE BookEStore;

/*************************** CREATE TABLES ***************************/
CREATE TABLE TACGIA (
  ID nvarchar(3) NOT NULL,
  NAME nvarchar(64)
);

CREATE TABLE DANHMUCSACH (
  ID nvarchar(2) NOT NULL,
  NAME nvarchar(64)
);

CREATE TABLE THONGTINSACH (
  ID nvarchar(4) NOT NULL,
  NAME nvarchar(256) NOT NULL,
  IMAGE nvarchar(256),
  PRICE float,
  VIEWS int,
  SALES int,
  INVENTORY int,
  DESCRIPTION nvarchar(512),
  AUTHOR nvarchar(3),
  CATERY nvarchar(2),
  PUBLISHER nvarchar(128)
);

CREATE TABLE NGUOIDUNG (
  ID nvarchar(4) NOT NULL,
  NAME nvarchar(64),
  EMAIL nvarchar(64),
  PASSWORD nvarchar(128) NOT NULL
);

CREATE TABLE DONHANG (
  ID nvarchar(6) NOT NULL,
  USER nvarchar(4) NOT NULL,
  DATE_CREATED date,
  CONTENT nvarchar(1024),
  TOTAL_COST double NOT NULL,
  STATE int
);

/*************************** SET CONSTRAINT ***************************/
ALTER TABLE TACGIA ADD CONSTRAINT PK_TACGIA PRIMARY KEY (ID);

ALTER TABLE DANHMUCSACH ADD CONSTRAINT PK_DANHMUCSACH PRIMARY KEY (ID);

ALTER TABLE THONGTINSACH ADD CONSTRAINT PK_THONGTINSACH PRIMARY KEY (ID);
ALTER TABLE THONGTINSACH ADD CONSTRAINT FK_THONGTINSACH_TACGIA FOREIGN KEY (AUTHOR) REFERENCES TACGIA(ID);
ALTER TABLE THONGTINSACH ADD CHECK (PRICE >= 0 AND VIEWS >=0 AND SALES >= 0 AND INVENTORY >= 0);

ALTER TABLE NGUOIDUNG ADD CONSTRAINT PK_NGUOIDUNG PRIMARY KEY (ID);

ALTER TABLE DONHANG ADD CONSTRAINT PK_DONHANG PRIMARY KEY (ID);
ALTER TABLE DONHANG ADD CONSTRAINT FK_DONHANG_NGUOIDUNG FOREIGN KEY (USER) REFERENCES NGUOIDUNG(ID);
ALTER TABLE DONHANG ADD CHECK (TOTAL_COST >= 0);
