USE BookEStore;
CREATE TABLE TACGIA (
  ID char(3) NOT NULL,
  NAME varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
);

CREATE TABLE DANHMUCSACH (
  ID char(2) NOT NULL,
  NAME varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci
);

CREATE TABLE NHAXUATBAN (
  ID char(3) NOT NULL,
  NAME varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci
);

CREATE TABLE THONGTINSACH (
  ID char(4) NOT NULL,
  NAME varchar(255) NOT NULL CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  IMAGE varchar(255),
  PRICE float,
  VIEWS int,
  SALES int,
  INVENTORY int,
  DESCRIPTION text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  AUTHOR char(3),
  CATEGORY char(2),
  PUBLISHER char(3)
);

CREATE TABLE NGUOIDUNG (
  ID char(4) NOT NULL,
  NAME varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  EMAIL varchar(64),
  PASSWORD varchar(128) NOT NULL
);

CREATE TABLE DONHANG (
  ID char(6) NOT NULL,
  USER char(4) NOT NULL,
  DATE_CREATED date NOT NULL,
  CONTENT varchar(1024) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  TOTAL_COST double NOT NULL,
  STATE int NOT NULL
);

/*************************** SET CONSTRAINT ***************************/
ALTER TABLE TACGIA ADD PRIMARY KEY (ID);

ALTER TABLE DANHMUCSACH ADD PRIMARY KEY (ID);

ALTER TABLE NHAXUATBAN ADD PRIMARY KEY (ID);

ALTER TABLE THONGTINSACH PRIMARY KEY (ID);
ALTER TABLE THONGTINSACH ADD FOREIGN KEY (AUTHOR) REFERENCES TACGIA(ID);
ALTER TABLE THONGTINSACH ADD FOREIGN KEY (CATEGORY) REFERENCES DANHMUCSACH(ID);
ALTER TABLE THONGTINSACH ADD FOREIGN KEY (PUBLISHER) REFERENCES NHAXUATBAN(ID);
ALTER TABLE THONGTINSACH ADD CHECK (PRICE >= 0 AND VIEWS >=0 AND SALES >= 0 AND INVENTORY >= 0);

ALTER TABLE NGUOIDUNG ADD PRIMARY KEY (ID);

ALTER TABLE DONHANG ADD PRIMARY KEY (ID);
ALTER TABLE DONHANG ADD FOREIGN KEY (USER) REFERENCES NGUOIDUNG(ID);
ALTER TABLE DONHANG ADD CHECK (TOTAL_COST >= 0 AND STATE IN('0','1','2','3'));
